export const FETCH_PRODUCT_DATA = 'FETCH_PRODUCT_DATA';
export const CATEGORY_DATA = 'CATEGORY_DATA';
export const CATEGORY_WISE_DATA = 'CATEGORY_WISE_DATA';
export const APPLY_FILTER_RATING_WISE = 'APPLY_FILTER_RATING_WISE';
export const APPLY_FILTER_STOCK_WISE = 'APPLY_FILTER_STOCK_WISE';
export const FILTER_DATA_WITH_RATE_AND_STOCK =
  'FILTER_DATA_WITH_RATE_AND_STOCK';
export const SEARCH_STRING = 'SEARCH_STRING';
